### ISSUE TITLE
h-m-m --config doesn't work

### ISSUE THREAD

**Issue by sofomryu** [nadrad/h-m-m#42]
![conf_terminal](https://user-images.githubusercontent.com/69798848/200226191-abd8fced-7329-4102-baca-f0ccc7c897a8.png)
![inside_hmm_conf](https://user-images.githubusercontent.com/69798848/200226203-b5e9e569-6790-4414-a69f-5fac42188e0b.png)

To adjucst h-m-m.conf I typed "h-m-m --config=./.h-m-m.conf". Instead of adjusting the conf, it opens h-m-m with title of weird message.

![lock_terminal](https://user-images.githubusercontent.com/69798848/200226421-0170093c-7068-4c97-b3c8-f459ddf975a1.png)
![inside_hmm_lock](https://user-images.githubusercontent.com/69798848/200226443-b9b98d2b-baee-42bc-b1a0-9efcd07f1c88.png)

To check if another h-m-m option work, I typed "h-m-m --focus-lock=true test" What I expected is that hmm file titled test is opened with focus lock setting on. Instead, it opens hmm file titled --focus-lock=true as you can see from the screenshot. 

How can I adjust them?

I'm using pop-os 22.04

**Comment by nadrad** [comment]
Funny mistake... I had forgotten to change the way file names are read from the command line after adding the settings. The settings were working fine actually, and the problem was with the file name. 

Anyway, it's fixed now.

**Comment by sofomryu** [comment]
Hi! Thanks for the feedback. h-m-m --focus-lock=true file.name works! However, setting config file as h-m-m --config=/path still doesn't work.
